### ISSUE TITLE
outputformat

### ISSUE THREAD

**Issue by vlasvlasvlas** [nathancahill/pikaday-skeleton#1]
Hi! love this extension! 

but how do i modify the way selected date is formatted? i mean output format

now: ex: Wed Sep 09 2015

i need something like YYYY-MM-DD

**Comment by nathancahill** [comment]
Ah, you'll have to look at [dbushell/Pikaday](https://github.com/dbushell/Pikaday). This is just compatibility CSS for [Skeleton](http://getskeleton.com/).

But regardless, you'll need to install [Moment.js](http://momentjs.com/), and then add an option like this to your Pikaday configuration:

```
format: 'YYYY-MM-DD'
```

**Comment by vlasvlasvlas** [comment]
oh okey i do have format: 'YYYY-MM-DD' but my output was ex: "Mon Sep 21 2015"

so with moment.js this will work out ? txs!
